INSERT INTO uneti.mon_hoc_phan (id, ten_mon_hoc_phan, so_tin_chi) VALUES (1, 'Cơ sở dữ liệu', 4);
INSERT INTO uneti.mon_hoc_phan (id, ten_mon_hoc_phan, so_tin_chi) VALUES (2, 'Kỹ thuật đồ hoạ máy tính', 2);
INSERT INTO uneti.mon_hoc_phan (id, ten_mon_hoc_phan, so_tin_chi) VALUES (3, 'Hệ điều hành', 3);
INSERT INTO uneti.mon_hoc_phan (id, ten_mon_hoc_phan, so_tin_chi) VALUES (4, 'Thực tập lập trình hướng đối tượng', 2);
INSERT INTO uneti.mon_hoc_phan (id, ten_mon_hoc_phan, so_tin_chi) VALUES (5, 'Tin cơ sở', 4);
INSERT INTO uneti.mon_hoc_phan (id, ten_mon_hoc_phan, so_tin_chi) VALUES (6, 'Quản trị học', 2);
INSERT INTO uneti.mon_hoc_phan (id, ten_mon_hoc_phan, so_tin_chi) VALUES (7, 'Logic học', 2);
INSERT INTO uneti.mon_hoc_phan (id, ten_mon_hoc_phan, so_tin_chi) VALUES (8, 'Pháp luật đại cương', 2);
INSERT INTO uneti.mon_hoc_phan (id, ten_mon_hoc_phan, so_tin_chi) VALUES (9, 'Tin học văn phòng', 2);
INSERT INTO uneti.mon_hoc_phan (id, ten_mon_hoc_phan, so_tin_chi) VALUES (10, 'Xác suất thống kê', 3);
INSERT INTO uneti.mon_hoc_phan (id, ten_mon_hoc_phan, so_tin_chi) VALUES (11, 'Vật lý', 4);
INSERT INTO uneti.mon_hoc_phan (id, ten_mon_hoc_phan, so_tin_chi) VALUES (12, 'Đại số tuyến tính', 2);
INSERT INTO uneti.mon_hoc_phan (id, ten_mon_hoc_phan, so_tin_chi) VALUES (13, 'Toán giải tích', 3);
INSERT INTO uneti.mon_hoc_phan (id, ten_mon_hoc_phan, so_tin_chi) VALUES (14, 'Thực tập lập trình cơ bản', 3);
INSERT INTO uneti.mon_hoc_phan (id, ten_mon_hoc_phan, so_tin_chi) VALUES (15, 'Triết học Mac - Lênin', 3);
INSERT INTO uneti.mon_hoc_phan (id, ten_mon_hoc_phan, so_tin_chi) VALUES (16, 'Xử lý tín hiệu số', 2);
INSERT INTO uneti.mon_hoc_phan (id, ten_mon_hoc_phan, so_tin_chi) VALUES (17, 'Toán rời rạc', 3);
INSERT INTO uneti.mon_hoc_phan (id, ten_mon_hoc_phan, so_tin_chi) VALUES (18, 'Lập trình hướng đối tượng', 3);
INSERT INTO uneti.mon_hoc_phan (id, ten_mon_hoc_phan, so_tin_chi) VALUES (19, 'Kiến trúc máy tính', 3);
INSERT INTO uneti.mon_hoc_phan (id, ten_mon_hoc_phan, so_tin_chi) VALUES (20, 'Cấu trúc dữ liệu và giải thuật', 3);
INSERT INTO uneti.mon_hoc_phan (id, ten_mon_hoc_phan, so_tin_chi) VALUES (21, 'Kinh tế chính trị Mac - Lê Nin', 2);
