INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (1, 'Tin 14A6 ', 1, 33);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (2, 'Tin 14A7', 1, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (3, 'Tin 14a1', 1, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (4, 'Tin 14A2', 1, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (5, 'Tin 14A3', 1, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (6, 'Tin 14A4', 1, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (7, 'Tin 14A5', 1, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (8, 'Tin 14A8', 1, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (9, 'Tin 14A9', 1, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (10, 'Tin 14A10', 1, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (11, 'QTKD 14A1', 4, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (12, 'QTKD 14A2', 4, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (13, 'QTKD 14A3', 4, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (14, 'QTKD 14A4', 4, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (15, 'KT 14A1', 2, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (16, 'KT 14A2', 2, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (17, 'KT 14A3', 2, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (18, 'KT 14A4', 2, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (19, 'KT 14A5', 2, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (20, 'CK 14A1', 10, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (21, 'CK 14A2', 10, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (22, 'CK 14A3', 10, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (23, 'KT CDT 14A1', 7, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (24, 'KT CDT 14A2', 7, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (25, 'KT CDT 14A3', 7, null);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (41, 'CNTP A1', 6, 16);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (42, 'CNTP A2', 6, 17);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (43, 'CNTP A3', 6, 18);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (45, 'DL&KS A2', 7, 20);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (46, 'DL&KS A3', 7, 21);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (47, 'Kế Toán A1', 8, 22);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (48, 'Kế Toán A2', 8, 23);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (49, 'Kế Toán A3', 8, 24);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (50, 'QTKD A1', 9, 25);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (51, 'QTKD A2', 9, 26);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (52, 'QTKD A3', 9, 27);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (53, 'TC - NH A1', 10, 28);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (56, 'KHCB A1', 11, 31);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (57, 'KHCB A2', 11, 32);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (58, 'KHCB A3', 11, 33);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (59, 'NN A1', 12, 34);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (60, 'NN A2', 12, 35);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (61, 'NN A3', 12, 36);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (62, 'LLCT A1', 13, 37);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (63, 'LLCT A2', 13, 38);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (64, 'LLCT A3', 13, 39);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (65, 'GDTC A1', 14, 40);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (66, 'GDTC A2', 14, 41);
INSERT INTO uneti.lop_bien_che (id, ten_lop, ma_khoa, ma_giang_vien) VALUES (67, 'GDTC A3', 14, 42);
