INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (16, 'T', 'Trần Văn', 1, '2001-12-02', 1);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (17, 'K', 'Nguyễn Công Mạnh', 1, '2002-10-10', 1);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (18, 'Đ', 'Đỗ Văn', 1, '2002-11-09', 1);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (20, 'T', 'Bùi Văn', 1, '1986-12-03', 1);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (21, 'N', 'Nguyễn Thị', 2, '1985-10-01', 0);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (22, 'H', 'Võ Thu', 3, '1988-03-05', 0);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (23, 'C', 'Lưu Khánh', 4, '1983-02-22', 1);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (24, 'H', 'Phùng Thị Lan', 5, '1981-07-30', 0);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (25, 'Q', 'Đặng Thị Thanh', 6, '1984-11-13', 0);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (26, 'H', 'Bùi Huy', 7, '1985-04-26', 1);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (27, 'Q', 'Nguyễn Hữu', 8, '1980-10-31', 1);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (28, 'H', 'Vũ Duy', 9, '1982-11-10', 1);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (31, 'T', 'Đoàn Kim', 9, '1987-06-17', 0);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (32, 'H', 'Đường Thị Thanh', 10, '1985-11-11', 0);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (33, 'A', 'Nguyễn Ngọc', 10, '1986-08-06', 0);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (34, 'G', 'Đặng Hương', 10, '1987-06-17', 0);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (35, 'D', 'Tạ Thị Ngọc', 11, '1985-11-07', 0);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (36, 'L', 'Đỗ Thị Tuyết', 11, '1986-07-06', 0);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (37, 'T', 'Nguyễn Thị', 11, '1987-01-17', 0);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (38, 'H', 'Lê Xuân', 12, '1985-08-07', 1);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (39, 'Y', 'Trần Thị Hoàng', 12, '1985-07-27', 0);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (40, 'L', 'Hoàng Thị Minh', 13, '1985-11-28', 0);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (41, 'N', 'Phạm Hồng', 13, '1986-03-06', 0);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (42, 'N', 'Bùi Thị', 13, '1986-01-18', 0);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (43, 'C', 'Phạm Cao', 14, '1983-03-13', 1);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (44, 'T', 'Trần Trọng', 14, '1985-07-15', 1);
INSERT INTO uneti.giang_vien (id, ten, ho, ma_khoa, ngay_sinh, gioi_tinh) VALUES (45, 'T', 'Bùi Lệ', 14, '1984-04-01', 0);
